conmon: fix run podman failed on rt kernel
Run podman on RT kernel failed
...
root@intel-x86-64:~# podman run --tls-verify=false hello-world
✔ docker.io/library/hello-world:latest
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob 2db29710123e done
Copying config feb5d9fea6 done
Writing manifest to image destination
Storing signatures
bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
IPv6: ADDRCONF(NETDEV_CHANGE): veth6f11f564: link becomes ready
IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
cni-podman0: port 1(veth6f11f564) entered blocking state
cni-podman0: port 1(veth6f11f564) entered disabled state
device veth6f11f564 entered promiscuous mode
cni-podman0: port 1(veth6f11f564) entered blocking state
cni-podman0: port 1(veth6f11f564) entered forwarding state
IPv4: martian source 10.88.0.2 from 10.88.0.2, on dev eth0
ll header: 00000000: ff ff ff ff ff ff 8a 2b 79 9f 29 e3 08 06
Error: error attaching to container 7f056504d9115ba6048164efd2c3322bf4514150dd4469c4371891f0409aa593: read unixpacket @->/proc/self/fd/11/attach: read: connection reset by peer
...

Backport a fix from upstream could fix the issue

Issue: LIN1022-3896
(LOCAL REV: NOT UPSTREAM) - WRLx specific

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>